version: 0.0
os: linux
files:
  - source: /
    destination: /home/app/current
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/app
    pattern: '**'
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: docker-stop.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: deploy-be.sh
      timeout: 300
      runas: root
